version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=property_db
      - DB_PORT=3306
      - NODE_ENV=development
      - PORT=3002
      - LOG_LEVEL=info
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mysql
    networks:
      - property-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=property_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - property-network

networks:
  property-network:
    driver: bridge

volumes:
  mysql-data: 