import Joi from 'joi';
import { IClearPropertyDetail } from '../types/property.types';

export const propertySchema = Joi.object<IClearPropertyDetail>({
  property_id: Joi.number().required(),
  call_us: Joi.string().allow('').optional(),
  exe_name: Joi.string().allow('').optional(),
  exe_email: Joi.string().email().allow('').optional(),
  exe_contact_no: Joi.string().allow('').optional(),
  exe_address: Joi.string().allow('').optional(),
  owner_name: Joi.string().allow('').optional(),
  owner_email: Joi.string().email().allow('').optional(),
  owner_contact_no: Joi.string().allow('').optional(),
  owner_address: Joi.string().allow('').optional(),
  pro_curr_status: Joi.string().allow('').optional(),
  prop_avail: Joi.string().allow('').optional(),
  permi_avail: Joi.string().allow('').optional(),
  project_unit: Joi.string().allow('').optional(),
  floor_loc: Joi.string().allow('').optional(),
  prop_ownership: Joi.string().allow('').optional(),
  flooring_type: Joi.string().allow('').optional(),
  facing: Joi.string().allow('').optional(),
  no_of_lift: Joi.string().allow('').optional(),
  no_of_bedrooms: Joi.string().allow('').optional(),
  no_of_bathrooms: Joi.string().allow('').optional(),
  no_of_balconies: Joi.string().allow('').optional(),
  no_of_open_sides: Joi.string().allow('').optional(),
  kitchen_detail: Joi.string().allow('').optional(),
  furniture_detail: Joi.string().allow('').optional(),
  age_of_property: Joi.string().allow('').optional(),
  power_supply: Joi.string().allow('').optional(),
  security_guards: Joi.string().allow('').optional(),
  camera: Joi.string().allow('').optional(),
  fire_avai: Joi.string().allow('').optional(),
  water_supply: Joi.string().allow('').optional(),
  water_timing: Joi.string().allow('').optional(),
  road_width: Joi.string().allow('').optional(),
  parking_detail: Joi.string().allow('').optional(),
  gas_supply: Joi.string().allow('').optional(),
  amenities: Joi.string().allow('').optional(),
  otheramenities: Joi.string().allow('').optional(),
  client_avail: Joi.string().allow('').optional(),
  overlooking: Joi.string().allow('').optional(),
  some_features: Joi.string().allow('').optional(),
  wardrobe: Joi.string().allow('').optional(),
  beds: Joi.string().allow('').optional(),
  fans: Joi.string().allow('').optional(),
  light: Joi.string().allow('').optional(),
  m_kitchen: Joi.string().allow('').optional(),
  fridge: Joi.string().allow('').optional(),
  ac: Joi.string().allow('').optional(),
  geyser: Joi.string().allow('').optional(),
  tv: Joi.string().allow('').optional(),
  stove: Joi.string().allow('').optional(),
  washing_machine: Joi.string().allow('').optional(),
  water_purifier: Joi.string().allow('').optional(),
  microwave: Joi.string().allow('').optional(),
  curtains: Joi.string().allow('').optional(),
  chimney: Joi.string().allow('').optional(),
  exhaust_fan: Joi.string().allow('').optional(),
  sofa: Joi.string().allow('').optional(),
  dinning_table: Joi.string().allow('').optional(),
  super_plot_area: Joi.string().allow('').optional(),
  super_plot_area_unit: Joi.string().allow('').optional(),
  super_con_area: Joi.string().allow('').optional(),
  super_con_area_unit: Joi.string().allow('').optional(),
  carpet_plot_area: Joi.string().allow('').optional(),
  carpet_plot_area_unit: Joi.string().allow('').optional(),
  carpet_con_area: Joi.string().allow('').optional(),
  carpet_con_area_unit: Joi.string().allow('').optional(),
  offer_price: Joi.number().allow(null).optional(),
  offer_price_unit: Joi.string().required(),
  expected_rent: Joi.string().allow('').optional(),
  expected_rent_unit: Joi.string().allow('').optional(),
  rent_security: Joi.string().allow('').optional(),
  rent_security_unit: Joi.string().allow('').optional(),
  maint_charge: Joi.string().allow('').optional(),
  maint_charge_unit: Joi.string().allow('').optional(),
  tax_charge: Joi.string().allow('').optional(),
  tax_charge_unit: Joi.string().allow('').optional(),
  other_charge: Joi.string().allow('').optional(),
  google_map: Joi.string().allow('').optional(),
  school: Joi.string().allow('').optional(),
  college: Joi.string().allow('').optional(),
  hospital: Joi.string().allow('').optional(),
  bank: Joi.string().allow('').optional(),
  brts_stop: Joi.string().allow('').optional(),
  r_station: Joi.string().allow('').optional(),
  m_station: Joi.string().allow('').optional(),
  airport: Joi.string().allow('').optional(),
  brochure: Joi.string().allow('').optional(),
  post_date: Joi.date().required(),
  pricerequest: Joi.string().valid('0', '1').required(),
  main_charges: Joi.number().allow(null).optional(),
  main_charges_unit: Joi.string().allow('').optional(),
  parkingdetail: Joi.string().allow('').optional(),
  custom_tag: Joi.string().max(255).allow('').optional(),
});

export const validateProperty = (data: IClearPropertyDetail) => {
  return propertySchema.validate(data, { abortEarly: false });
}; 